version: '3'

services:
    rhythm-bot-server:
        image: docker.pkg.github.com/Malexion/Rhythm-Bot/bot:latest
        environment:
            STREAM_VOLUME: 0.05
        # read in DISCORD_TOKEN from dotenv
        env_file: .env
